### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by catfoolyou** [PeytonPlayz595/eagler-optifine#2]
The client doesn't load, neither desktop nor HTML.

**Comment by PeytonPlayz595** [comment]
@catfoolyou Are there any errors in the console? And wdym be won't load, does it stay on the loading screen or does it not load at all?

**Comment by catfoolyou** [comment]
It stays on the screen at loading assets.

**Comment by PeytonPlayz595** [comment]
> It stays on the screen at loading assets.

Copy and paste the output of the Inspect Element console (Ctr + Shift + i)?
Make sure to use the website and not the offline download when you copy and paste the console, it's easier to debug.

**Comment by catfoolyou** [comment]
Will do.

**Comment by catfoolyou** [comment]
The offline client actually works on my personal PC but not on my school one, must be those shitty restrictions.
